vim.keymap.set('i', 'jj', '<Esc>')
vim.keymap.set('n', '<leader>w', '<cmd>w<cr>')
vim.keymap.set('n', '<leader>q', '<cmd>qa<cr>')
vim.keymap.set('n', '<leader>x', '<cmd>q<cr>')
vim.keymap.set('n', '<leader>s', 'i¯\\_(ツ)_/¯<Esc>')
vim.keymap.set('n', '<leader>,', '@@')
vim.keymap.set('v', '<leader>s"', 'xi""<esc>hp')
vim.keymap.set('v', '<leader>s{', 'xi{}<esc>hp')
vim.keymap.set('v', '<leader>s(', 'xi()<esc>hp')
vim.keymap.set('i', '{<cr>', '{<esc>o}<esc>O')
vim.keymap.set('i', '(<cr>', '(<esc>o)<esc>O')
vim.keymap.set('i', '[<cr>', '[<esc>o]<esc>O')
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.number = true
vim.bo.softtabstop = 2
